from network.bnn import BNN
from network.lan import LAN
from network.unet import UNet
from network.unet_2 import N2SUNet
from network.invDN import invDN
from network.UNetD import UNetD
from network.UNetG import UNetG
from network.DiscriminatorLinear import DiscriminatorLinear
from network.bnn import BNN_v2